/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
author: Nice2meetU2 (https://sketchfab.com/Nice2meetU2)
license: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
source: https://sketchfab.com/3d-models/japanese-cherry-tree-ca5a9449555e490cbe726671ed8f95a4
title: Japanese Cherry tree
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function FarTree(props) {
  const { nodes, materials } = useGLTF('/models/FarTree/scene.gltf')
  return (
    <group {...props} dispose={null}>
      <group rotation={[-Math.PI / 2, 0, 0]}>
        <group rotation={[Math.PI / 2, 0, 0]}>
          <mesh geometry={nodes.Object_4.geometry} material={materials['Material.002']} />
          <mesh geometry={nodes.Object_5.geometry} material={materials.Material} />
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('/models/FarTree/scene.gltf')
