/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
author: Dmitriy Baturinets (https://sketchfab.com/Baturinets)
license: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
source: https://sketchfab.com/3d-models/japanese-street-lamp-de9e13e35b504fea84b51857adb2e8b0
title: Japanese street lamp
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function Lamp(props) {
  const { nodes, materials } = useGLTF('/models/Lamp/scene.gltf')
  return (
    <group {...props} dispose={null}>
      <group rotation={[Math.PI / 2, 0, -Math.PI]}>
        <group rotation={[-Math.PI, 0, 0]} scale={0.01}>
          <mesh geometry={nodes.SM_StreetLight__0.geometry} material={materials['Scene_-_Root']} >
          </mesh>
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('/models/Lamp/scene.gltf')
