/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
author: Sahir Virmani (https://sketchfab.com/sahirvirmani)
license: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
source: https://sketchfab.com/3d-models/japanese-torii-gate-2027a248de1b4b70985ff97e708fb50d
title: Japanese Torii Gate
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function Torii(props) {
  const { nodes, materials } = useGLTF('/models/Torii/scene.gltf')
  return (
    <group {...props} dispose={null}>
      <group rotation={[-Math.PI / 2, 0, 0]}>
        <group rotation={[Math.PI / 2, 0, 0]}>
          <group position={[-380.48, 429.59, -2.81]} rotation={[-Math.PI / 2, 0, 0]} scale={100}>
            <mesh geometry={nodes.Cylinder_torii_0.geometry} material={materials.torii} />
          </group>
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('/models/Torii/scene.gltf')
