/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
author: ZoeChuiYan (https://sketchfab.com/zoelofutureworks)
license: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
source: https://sketchfab.com/3d-models/organics-small-tree-81f88945fc274c0da9fea9d777e8beb6
title: Organics: Small Tree
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function Tree(props) {
  const { nodes, materials } = useGLTF('/models/Tree/scene.gltf')
  return (
    <group {...props} dispose={null}>
      <group rotation={[-Math.PI / 2, 0, 0]}>
        <mesh geometry={nodes.Object_2.geometry} material={materials.lambert2SG} />
        <mesh geometry={nodes.Object_3.geometry} material={materials.lambert3SG} />
      </group>
    </group>
  )
}

useGLTF.preload('/models/Tree/scene.gltf')
